name: Meson Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Meson tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Meson and Ninja
        run: |
          python -m pip install --upgrade pip                              
          pip install meson ninja                                          
                                                                           
      - name: Setup build directory                                    
        run: meson setup build                                             
                                                                           
      - name: Build                                                        
        run: meson compile -C build                                        
                                                                           
      - name: Run tests                                                    
        run: meson test -C build --print-errorlogs 
